CREATE TABLE `SM_DICT_TYPE` (
	`ID` INT(11) NOT NULL AUTO_INCREMENT COMMENT '主键',
	`TYPE_CODE` VARCHAR(50) NOT NULL COMMENT '字典类型代码',
	`TYPE_NAME` VARCHAR(100) NOT NULL COMMENT '字典类型名称',
	`STATUS` INT(1) NOT NULL COMMENT '状态，0：禁用；1：启用',
	`REMARK` VARCHAR(500) COMMENT '备注',
	`CREATOR` VARCHAR(50) COMMENT '创建人',
	`CREATE_TIME` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
	`MODIFIER` VARCHAR(50) COMMENT '修改人',
	`MODIFY_TIME` DATETIME COMMENT '修改时间',
	PRIMARY KEY (`ID`),
	UNIQUE INDEX `TYPE_CODE` (`TYPE_CODE`)
)
COMMENT='数据字典类型表'
;