CREATE TABLE SMS_USER (
	ID BIGINT(20) AUTO_INCREMENT PRIMARY KEY COMMENT '主键',
	USERNAME VARCHAR(50) NOT NULL UNIQUE COMMENT '用户名',
	PASSWORD VARCHAR(128) NOT NULL COMMENT '密码',
	NAME VARCHAR(50) NOT NULL COMMENT '名称',
	SEX CHAR(1) DEFAULT '1' COMMENT '性别，0：男；1：女',
	BIRTHDAY DATE COMMENT '生日',
	CREATOR VARCHAR(50) COMMENT '创建人',
	CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
	MODIFIER VARCHAR(50) COMMENT '修改人',
	MODIFY_TIME TIMESTAMP COMMENT '修改时间',
	STATUS INT(1) NOT NULL COMMENT '状态，0：禁用；1：启用'
)
COMMENT = '用户表'
;